version: '3.8'

services:
  # PostgreSQL database service
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # gRPC server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
    ports:
      - "50051:50051"

  # gRPC client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    # Using stdin_open and tty to keep the container running and allow for user input
    stdin_open: true
    tty: true

volumes:
  postgres_data: